# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c591cae621588373d650cde3ec315fad7ae0629616be521c3b8f21edfc0d69cc297022ccbfc20aae98c008b2c861b77104a92b0669afa2eeadd5a23e2bdddd15

test:
  secret_key_base: 31bae0fe3903b8059fe3c02847123f50210c154260a6bcfa28f1e6341236b7085921f18025d1d39863624b28690b703a159c26d464aedfe33fb662bff525f250

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
